[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
urlencoding = "2.1"
dotenvy = "0.15"
rand = "0.8"
url = "2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
walkdir = "2"
regex = "1"
audiotags = "0.5"
lofty = "0.21"
base64 = "0.22"
sha2 = "0.10"
mp3-duration = "0.1"
symphonia = { version = "0.5", features = ["aac", "mp3", "isomp4", "flac", "ogg", "vorbis", "wav", "pcm"] }
rustfft = "6"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
id3 = "1"

